# Generated by Django 5.0.4 on 2024-04-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_work_customuser_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='work',
        ),
        migrations.AddField(
            model_name='customuser',
            name='work',
            field=models.ManyToManyField(related_name='user_works', to='users.work'),
        ),
    ]
