# Generated by Django 5.0.4 on 2024-04-10 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_work_customuser_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='work',
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
