# Generated by Django 5.0.4 on 2024-04-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_attachments_task_task_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(null=True, to='tasks.comments'),
        ),
    ]
