# Generated by Django 5.0.4 on 2024-04-07 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_assign_by_task_assign_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ManyToManyField(related_name='tasks_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
