# Generated by Django 5.0.4 on 2024-04-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='src',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='src',
        ),
        migrations.RemoveField(
            model_name='memberdetail',
            name='img',
        ),
        migrations.AddField(
            model_name='attachments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/', verbose_name='attachments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='imag',
            field=models.ImageField(blank=True, null=True, upload_to='member/', verbose_name='member'),
        ),
    ]
