# Generated by Django 5.0.4 on 2024-04-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_attachments_src_remove_comments_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='taskcover/', verbose_name='taskcover'),
        ),
    ]
