# Generated by Django 5.0.4 on 2024-04-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
